/**
 * build-client.mjs — generate `lib/client.js` (the browser half).
 *
 * The browser half is not plain ESM: the page evaluates it and it registers a
 * factory on the shared module loader, exactly like the shipped community
 * plugins do:
 *
 *   window.__ModuleLoader__.load({ id, factory: (require) => { ... return module.exports } })
 *
 * The factory only touches the official `locale` service (no React, no
 * externals), so no bundler is required and the artifact stays auditable.
 *
 * Inputs:
 *   locales/ar.json       { "<namespace>": { "<key>": "<Arabic>" } }
 *   data/en-catalog.json  { "<namespace>": { "<key>": "<English>" } }
 *
 * Run: node scripts/build-client.mjs [--check]
 *   --check  verify key parity and fail without writing (used by CI/tests)
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const AR_PATH = join(ROOT, 'locales', 'ar.json')
const EN_PATH = join(ROOT, 'data', 'en-catalog.json')
const OUT_PATH = join(ROOT, 'lib', 'client.js')
const LOCALE_ID = 'ar'
const LOCALE_LABEL = 'العربية'

const check = process.argv.includes('--check')

const arabic = JSON.parse(readFileSync(AR_PATH, 'utf8'))
const english = JSON.parse(readFileSync(EN_PATH, 'utf8'))

/* ------------------------------------------------------------- validation --- */

const problems = []
let translated = 0
let missing = 0
let extra = 0

for (const [ns, enDict] of Object.entries(english)) {
  const arDict = arabic[ns]
  if (!arDict) {
    problems.push(`missing namespace: ${ns} (${Object.keys(enDict).length} keys)`)
    missing += Object.keys(enDict).length
    continue
  }
  for (const key of Object.keys(enDict)) {
    const en = enDict[key]
    const hasCopy = typeof en === 'string' && en.trim().length > 0
    if (typeof arDict[key] !== 'string' || (hasCopy && !arDict[key].trim())) {
      problems.push(`missing translation: ${ns}#${key}`)
      missing++
    } else {
      translated++
      // Placeholders must survive translation byte-for-byte.
      const vars = (s) => (s.match(/\{[a-zA-Z0-9_.]+\}|%s|\{\{?[a-zA-Z0-9_]+\}?\}/g) || []).sort().join(',')
      if (vars(en) !== vars(arDict[key])) {
        problems.push(`placeholder mismatch: ${ns}#${key} — en:[${vars(en)}] ar:[${vars(arDict[key])}]`)
      }
    }
  }
}
for (const ns of Object.keys(arabic)) {
  if (!english[ns]) continue
  for (const key of Object.keys(arabic[ns])) {
    if (!(key in english[ns])) { problems.push(`unknown key: ${ns}#${key}`); extra++ }
  }
}

const summary = `namespaces ${Object.keys(english).length} · keys ${translated + missing} · translated ${translated} · missing ${missing} · extra ${extra}`
console.log(summary)

if (check) {
  if (problems.length) {
    console.error(`\n${problems.length} problem(s):`)
    for (const p of problems.slice(0, 40)) console.error('  ' + p)
    if (problems.length > 40) console.error(`  ... and ${problems.length - 40} more`)
    process.exit(1)
  }
  console.log('catalog is complete and consistent')
  process.exit(0)
}

/* -------------------------------------------------------------- artifact --- */

const clientSource = `/**
 * dsh-arabic — browser half (generated by scripts/build-client.mjs; do not edit).
 *
 * 1. Registers the "ar" language and its dictionaries through the official
 *    \`locale\` service. Keys we do not translate fall back to English.
 * 2. Adds one preference row to Settings → General that switches the bidi/RTL
 *    layer off and on. The layer itself lives in the page (injected by the host
 *    half) and exposes \`window.__dshArabic\`; the row is only its control, and
 *    it is registered defensively so a future slot change can never take the
 *    language pack down with it.
 */
window.__ModuleLoader__.load({
  id: 'dsh-arabic',
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
    var LOCALE_ID = ${JSON.stringify(LOCALE_ID)};
    var LOCALE_LABEL = ${JSON.stringify(LOCALE_LABEL)};
    var ROW_ID = 'dsh-arabic';
    var DICTS = ${JSON.stringify(arabic)};

    /** True while the interface language is Arabic (drives the row's own copy). */
    function isArabicActive(ctx) {
      try {
        return String(ctx.locale.getSnapshot().active).toLowerCase().indexOf('ar') === 0;
      } catch (err) {
        return false;
      }
    }

    /** Settings → General → <row>. Optional surface, never required. */
    function registerSettingsRow(ctx) {
      if (!ctx || !ctx.slots || typeof ctx.slots.inject !== 'function') return false;
      var React = require('react');
      var primitives = require('@deepseek-ai/dsh-client-ui-primitives');
      var Switch = primitives && primitives.Switch;
      if (!React || typeof React.createElement !== 'function' || !Switch) return false;

      function RtlRow() {
        var enabledState = React.useState(function () {
          try { return !window.__dshArabic || window.__dshArabic.isEnabled(); } catch (err) { return true; }
        });
        var enabled = enabledState[0];
        var setEnabled = enabledState[1];
        var tickState = React.useState(0);
        var setTick = tickState[1];

        React.useEffect(function () {
          var unsubscribe = null;
          try {
            unsubscribe = ctx.locale.subscribe(function () { setTick(function (n) { return n + 1; }); });
          } catch (err) {}
          function onLayerChange(event) {
            var next = event && event.detail ? event.detail.enabled : null;
            if (typeof next === 'boolean') setEnabled(next);
          }
          try { window.addEventListener('dsh-arabic:change', onLayerChange); } catch (err) {}
          return function () {
            try { if (unsubscribe) unsubscribe(); } catch (err) {}
            try { window.removeEventListener('dsh-arabic:change', onLayerChange); } catch (err) {}
          };
        }, []);

        var ar = isArabicActive(ctx);
        var title = ar ? 'اتجاه النص من اليمين إلى اليسار' : 'Right-to-left text direction';
        var description = ar
          ? 'يرتّب النص العربي والإنجليزي المختلط في كل فقرة على حدة، ويُبقي كتل الكود من اليسار إلى اليمين.'
          : 'Orders mixed Arabic and English text paragraph by paragraph, and keeps code blocks left-to-right.';

        return React.createElement('div', {
          style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '16px' }
        },
          React.createElement('div', { style: { display: 'flex', flexDirection: 'column', gap: '2px', minWidth: 0 } },
            React.createElement('div', { style: { fontSize: '13px', fontWeight: 500 } }, title),
            React.createElement('div', { style: { fontSize: '12px', opacity: 0.7 } }, description)
          ),
          React.createElement(Switch, {
            checked: enabled,
            label: title,
            onChange: function (next) {
              setEnabled(next);
              try { if (window.__dshArabic) window.__dshArabic.setEnabled(next); } catch (err) {}
            }
          })
        );
      }

      ctx.slots.inject('settings.general.item', function () {
        return ctx.slots.register({ name: 'settings.general.item', id: ROW_ID, order: 60 }, RtlRow);
      });
      return true;
    }

    exports.name = 'dsh-arabic';
    exports.inject = ['locale'];

    exports.apply = function (ctx) {
      ctx.effect(function () {
        var disposers = [];
        // The language must exist before its dictionaries are addressable, and
        // its fallback (en) must already be registered. Re-registering an
        // occupied id is a no-op we must absorb.
        try {
          disposers.push(ctx.locale.addLanguage({ id: LOCALE_ID, label: LOCALE_LABEL, fallback: 'en' }));
        } catch (err) {
          if (!/occupied|already/i.test(String(err && err.message))) throw err;
        }
        for (var ns of Object.keys(DICTS)) {
          try {
            disposers.push(ctx.locale.register(ns, LOCALE_ID, DICTS[ns]));
          } catch (err) {
            // A namespace we do not own, or one already taken for this locale.
            if (!/occupied|already/i.test(String(err && err.message))) throw err;
          }
        }
        return function () {
          for (var i = 0; i < disposers.length; i++) {
            try { disposers[i](); } catch (err) {}
          }
        };
      }, 'dsh-arabic: Arabic language pack');

      try { registerSettingsRow(ctx); } catch (err) {}
    };

    return module.exports;
  }
});
`

if (existsSync(OUT_PATH) && readFileSync(OUT_PATH, 'utf8') === clientSource) {
  console.log('lib/client.js already up to date')
  process.exit(0)
}
writeFileSync(OUT_PATH, clientSource)
console.log(`wrote lib/client.js (${(clientSource.length / 1024).toFixed(1)} KB, ${Object.keys(arabic).length} namespaces)`)
